/*
Navicat MySQL Data Transfer

Source Server         : almufti
Source Server Version : 50616
Source Host           : localhost:3306
Source Database       : dodin

Target Server Type    : MYSQL
Target Server Version : 50616
File Encoding         : 65001

Date: 2015-08-24 07:43:51
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `wilayah`
-- ----------------------------
DROP TABLE IF EXISTS `wilayah`;
CREATE TABLE `wilayah` (
  `kode_kab` varchar(10) DEFAULT NULL,
  `kabkota` varchar(30) DEFAULT NULL,
  `kode_kec` varchar(10) DEFAULT NULL,
  `kecamatan` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of wilayah
-- ----------------------------
INSERT INTO `wilayah` VALUES ('kode_kab', 'kabkota', 'kode_kec', 'kecamatan');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20501', 'Kec. Nanggung');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20502', 'Kec. Leuwiliang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20503', 'Kec. Pamijahan');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20521', 'Kec. Cibinong');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20522', 'Kec. Bojong Gede');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20523', 'Kec. Kemang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20524', 'Kec. Parung');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20525', 'Kec. Gunung Sindur');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20526', 'Kec. Rumpin');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20527', 'Kec. Cigudeg');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20528', 'Kec. Jasinga');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20529', 'Kec. Tenjo');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20530', 'Kec. Parungpanjang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20531', 'Kec. Tamansari');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20532', 'Kec. Ciseeng');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20533', 'Kec. Kelapa Nunggal');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20534', 'Kec. Sukajaya');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20535', 'Kec. Ranca Bungur');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20536', 'Kec. Tanjung Sari');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20537', 'Kec. Tajurhalang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20538', 'Kec. Cigombong');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20539', 'Kec. Leuwisadeng');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20540', 'Kec. Tenjolaya');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20601', 'Kec. Ciemas');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20602', 'Kec. Ciracap');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20603', 'Kec. Surade');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20604', 'Kec. Jampang Kulon');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20605', 'Kec. Kalibunder');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20606', 'Kec. Tegalbuleud');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20607', 'Kec. Cidolog');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20608', 'Kec. Sagaranten');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20609', 'Kec. Pabuaran');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20610', 'Kec. Lengkong');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20611', 'Kec. Pelabuhan Ratu');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20612', 'Kec. Warung Kiara');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20613', 'Kec. Jampang Tengah');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20614', 'Kec. Cikembar');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20615', 'Kec. Nyalindung');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20616', 'Kec. Gegerbitung');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20617', 'Kec. Sukaraja');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20618', 'Kec. Sukabumi');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20619', 'Kec. Kadudampit');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20620', 'Kec. Cisaat');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20621', 'Kec. Cibadak');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20622', 'Kec. Nagrak');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20623', 'Kec. Cicurug');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20624', 'Kec. Cidahu');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20625', 'Kec. Parakansalak');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20626', 'Kec. Parungkuda');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20627', 'Kec. Kalapa Nunggal');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20628', 'Kec. Cikidang');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20629', 'Kec. Cisolok');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20630', 'Kec. Kabandungan');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20631', 'Kec. Gunung Guruh');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20632', 'Kec. Cikakak');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20633', 'Kec. Bantar Gadung');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20634', 'Kec. Cicantayan');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20635', 'Kec. Simpenan');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20636', 'Kec. Kebon Pedes');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20637', 'Kec. Cidadap');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20638', 'Kec. Cibitung');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20639', 'Kec. Curugkembar');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21112', 'Kec. Cikajang');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21113', 'Kec. Banjarwangi');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21114', 'Kec. Cilawu');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21115', 'Kec. Bayongbong');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21116', 'Kec. Cisurupan');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21117', 'Kec. Samarang');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21119', 'Kec. Garut Kota');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21120', 'Kec. Karangpawitan');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21121', 'Kec. Wanaraja');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21122', 'Kec. Sukawening');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21123', 'Kec. Banyuresmi');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21124', 'Kec. Leles');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21125', 'Kec. Leuwigoong');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21126', 'Kec. Cibatu');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21127', 'Kec. Cibiuk');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21128', 'Kec. Kadungora');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21129', 'Kec. Blubur Limbangan');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21130', 'Kec. Selaawi');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21131', 'Kec. Malangbong');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21132', 'Kec. Mekarmukti');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21133', 'Kec. Caringin');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21134', 'Kec. Cihurip');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21135', 'Kec. Sukaresmi');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21136', 'Kec. Pasirwangi');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21137', 'Kec. Karangtengah');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21138', 'Kec. Kersamanah');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21139', 'Kec. Tarogong Kaler');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21140', 'Kec. Tarogong Kidul');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21141', 'Kec. Cigedug');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21142', 'Kec. Sucinaraja');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21143', 'Kec. Pangatikan');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21201', 'Kec. Cipatujah');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21202', 'Kec. Karangnunggal');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21203', 'Kec. Cikalong');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21204', 'Kec. Pancatengah');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21205', 'Kec. Cikatomas');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21206', 'Kec. Cibalong');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21207', 'Kec. Bantarkalong');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21208', 'Kec. Bojonggambir');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21209', 'Kec. Sodonghilir');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21210', 'Kec. Taraju');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21211', 'Kec. Salawu');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21212', 'Kec. Tanjungjaya');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21213', 'Kec. Sukaraja');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21214', 'Kec. Salopa');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21215', 'Kec. Cineam');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21216', 'Kec. Manonjaya');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21219', 'Kec. Singaparna');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21220', 'Kec. Cigalontang');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21613', 'Kec. Palasah');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21614', 'Kec. Jatiwangi');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21615', 'Kec. Dawuan');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21616', 'Kec. Panyingkiran');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21617', 'Kec. Kadipaten');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21618', 'Kec. Kertajati');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21619', 'Kec. Jatitujuh');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21620', 'Kec. Ligung');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21621', 'Kec. Sumberjaya');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21622', 'Kec. Banjaran');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21623', 'Kec. Cingambul');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21624', 'Kec. Malausma');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21625', 'Kec. Sindang');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21626', 'Kec. Kasokandel');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21701', 'Kec. Waled');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21702', 'Kec. Ciledug');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21703', 'Kec. Losari');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21704', 'Kec. Babakan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21705', 'Kec. Karang Sembung');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21706', 'Kec. Lemah Abang');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21707', 'Kec. Sedong');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21708', 'Kec. Astana Japura');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21709', 'Kec. Mundu');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21710', 'Kec. Beber');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21712', 'Kec. Sumber');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21713', 'Kec. Palimanan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21714', 'Kec. Plumbon');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21715', 'Kec. Weru');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21718', 'Kec. Kapetakan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21719', 'Kec. Klangenan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21720', 'Kec. Arjawinangun');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21721', 'Kec. Ciwaringin');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21722', 'Kec. Susukan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21723', 'Kec. Gegesik');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21724', 'Kec. Susukan Lebak');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21725', 'Kec. Pabedilan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21726', 'Kec. Dukupuntang');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21727', 'Kec. Panguragan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21728', 'Kec. Kaliwedi');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21729', 'Kec. Pangenan');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21730', 'Kec. Gebang');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21731', 'Kec. Depok');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21732', 'Kec. Kedawung');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21733', 'Kec. Karangwareng');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21734', 'Kec. Talun');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21735', 'Kec. Gunung Jati');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22124', 'Kec. Banyusari');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22125', 'Kec. Kotabaru');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22126', 'Kec. Cilamaya Wetan');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22127', 'Kec. Purwasari');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22128', 'Kec. Teluk Jambe Barat');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22129', 'Kec. Teluk Jambe Timur');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22130', 'Kec. Karawang Timur');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22131', 'Kec. Tegalwaru');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22132', 'Kec. Cilebar');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22133', 'Kec. Karawang Barat');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22201', 'Kec. Setu');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22203', 'Kec. Cibarusah');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22205', 'Kec. Kedung Waringin');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22207', 'Kec. Cibitung');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22209', 'Kec. Bebelan');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22210', 'Kec. Taruma Jaya');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22211', 'Kec. Tembelang');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22212', 'Kec. Sukatani');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22213', 'Kec. Pebayuran');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22214', 'Kec. Cabangbungin');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22215', 'Kec. Muara Gembong');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22216', 'Kec. Tambun Selatan');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22217', 'Kec. Tambun Utara');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22218', 'Kec. Cikarang Barat');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22219', 'Kec. Karang Bahagia');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22220', 'Kec. Cikarang Utara');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22221', 'Kec. Cikarang Selatan');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22222', 'Kec. Cikarang Timur');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22223', 'Kec. Bojong Mangu');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22224', 'Kec. Cikarang Pusat');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22225', 'Kec. Sukakarya');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22226', 'Kec. Sukawangi');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22227', 'Kec. Serang Baru');
INSERT INTO `wilayah` VALUES ('222', 'Kab. Bekasi', '22228', 'Kec. Tarumajaya');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22301', 'Kec. Rongga');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22302', 'Kec. Gununghalu');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22303', 'Kec. Sindangkerta');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22304', 'Kec. Cililin');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22305', 'Kec. Cihampelas');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22306', 'Kec. Cipongkor');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22307', 'Kec. Batujajar');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22308', 'Kec. Cipatat');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22309', 'Kec. Padalarang');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22310', 'Kec. Ngamprah');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22311', 'Kec. Parongpong');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22312', 'Kec. Lembang');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22313', 'Kec. Cisarua');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22314', 'Kec. Cikalong Wetan');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22315', 'Kec. Cipeundeuy');
INSERT INTO `wilayah` VALUES ('223', 'Kab. Bandung Barat', '22316', 'Kec. Saguling');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22551', 'KEC. CIJULANG');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22552', 'KEC. CIMERAK');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22553', 'KEC. CIGUGUR');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22554', 'KEC. LANGKAPLANCAR');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22555', 'KEC. MANGUNJAYA');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22556', 'KEC. PADAHERANG');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22557', 'KEC. KALIPUCANG');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22558', 'KEC. PANGANDARAN');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22559', 'KEC. SIDAMULIH');
INSERT INTO `wilayah` VALUES ('225', 'KAB. PANGANDARAN', '22560', 'KEC. PARIGI');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26001', 'Kec. Bandung Kulon');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26002', 'Kec. Babakan Ciparay');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26003', 'Kec. Bojong Loa Kaler');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26004', 'Kec. Bojong Loa Kidul');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26005', 'Kec. Astananyar');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26006', 'Kec. Regol');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26007', 'Kec. Lengkong');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26008', 'Kec. Bandung Kidul');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20504', 'Kec. Cibungbulang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20505', 'Kec. Ciampea');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20506', 'Kec. Dramaga');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20507', 'Kec. Ciomas');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20508', 'Kec. Cijeruk');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20509', 'Kec. Caringin');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20640', 'Kec. Purabaya');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20641', 'Kec. Cireunghas');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20642', 'Kec. Sukalarang');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20643', 'Kec. Caringin');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20644', 'Kec. Bojong Genteng');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20645', 'Kec. Waluran');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20646', 'Kec. Cimanggu');
INSERT INTO `wilayah` VALUES ('206', 'Kab. Sukabumi', '20647', 'Kec. Ciambar');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20701', 'Kec. Agrabinta');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20702', 'Kec. Sindang Barang');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20703', 'Kec. Cidaun');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20704', 'Kec. Naringgul');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20705', 'Kec. Cibinong');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20706', 'Kec. Tanggeung');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20707', 'Kec. Kadupandak');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20708', 'Kec. Takokak');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20709', 'Kec. Sukanagara');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20710', 'Kec. Pagelaran');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20711', 'Kec. Campaka');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20712', 'Kec. Cibeber');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20713', 'Kec. Warungkondang');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20714', 'Kec. Cilaku');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20715', 'Kec. Sukaluyu');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20717', 'Kec. Ciranjang');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20718', 'Kec. Mande');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20719', 'Kec. Karang Tengah');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20720', 'Kec. Cianjur');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20721', 'Kec. Cugenang');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20722', 'Kec. Pacet');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20723', 'Kec. Sukaresmi');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20724', 'Kec. Cikalong Kulon');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20725', 'Kec. Bojong Picung');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20726', 'Kec. Campaka Mulya');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20727', 'Kec. Cikadu');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20728', 'Kec. Leles');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20729', 'Kec. Cijati');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20730', 'Kec. Gekbrong');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20731', 'Kec. Cipanas');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20732', 'Kec. Haurwangi');
INSERT INTO `wilayah` VALUES ('207', 'Kab. Cianjur', '20733', 'Kec. Pasirkuda');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20801', 'Kec. Ciwidey');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20802', 'Kec. Pasirjambu');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20803', 'Kec. Cimaung');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20804', 'Kec. Pangalengan');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20805', 'Kec. Kertasari');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20806', 'Kec. Pacet');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20807', 'Kec. Ibun');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20808', 'Kec. Paseh');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20809', 'Kec. Cikancung');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20810', 'Kec. Cicalengka');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20811', 'Kec. Rancaekek');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20812', 'Kec. Majalaya');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20813', 'Kec. Ciparay');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20814', 'Kec. Baleendah');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20815', 'Kec. Arjasari');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20816', 'Kec. Banjaran');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20817', 'Kec. Pameungpeuk');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20818', 'Kec. Katapang');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20819', 'Kec. Soreang');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20820', 'Kec. Margaasih');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20821', 'Kec. Margahayu');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20822', 'Kec. Dayeuhkolot');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20823', 'Kec. Bojongsoang');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20824', 'Kec. Cileunyi');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20825', 'Kec. Cilengkrang');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20826', 'Kec. Cimenyan');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20829', 'Kec. Rancabali');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20830', 'Kec. Nagreg');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20831', 'Kec. Solokanjeruk');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20832', 'Kec. Cangkuang');
INSERT INTO `wilayah` VALUES ('208', 'Kab. Bandung', '20833', 'Kec. Kutawaringin');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21001', 'Kec. Jatinangor');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21002', 'Kec. Cimanggung');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21003', 'Kec. Tanjungsari');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21004', 'Kec. Rancakalong');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21005', 'Kec. Sumedang Selatan');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21006', 'Kec. Sumedang Utara');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21007', 'Kec. Situraja');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21008', 'Kec. Darmaraja');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21009', 'Kec. Cibugel');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21010', 'Kec. Wado');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21012', 'Kec. Tomo');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21013', 'Kec. Ujungjaya');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21014', 'Kec. Conggeang');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21015', 'Kec. Paseh');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21016', 'Kec. Cimalaka');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21017', 'Kec. Tanjungkerta');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21018', 'Kec. Buahdua');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21019', 'Kec. Ganeas');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21020', 'Kec. Jatigede');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21023', 'Kec. Pamulihan');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21024', 'Kec. Cisitu');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21025', 'Kec. Jatinunggal');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21026', 'Kec. Cisarua');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21027', 'Kec. Tanjungmedar');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21028', 'Kec. Surian');
INSERT INTO `wilayah` VALUES ('210', 'Kab. Sumedang', '21029', 'Kec. Sukasari');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21101', 'Kec. Talegong');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21102', 'Kec. Cisewu');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21103', 'Kec. Bungbulang');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21104', 'Kec. Pamulihan');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21105', 'Kec. Pakenjeng');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21106', 'Kec. Cikelet');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21107', 'Kec. Pameungpeuk');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21108', 'Kec. Cibalong');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21109', 'Kec. Cisompet');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21110', 'Kec. Peundeuy');
INSERT INTO `wilayah` VALUES ('211', 'Kab. Garut', '21111', 'Kec. Singajaya');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21221', 'Kec. Leuwisari');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21223', 'Kec. Cisayong');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21224', 'Kec. Rajapolah');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21225', 'Kec. Jamanis');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21226', 'Kec. Ciawi');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21227', 'Kec. Pagerageung');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21228', 'Kec. Parungponteng');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21229', 'Kec. Sariwangi');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21230', 'Kec. Sukaratu');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21231', 'Kec. Sukarame');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21232', 'Kec. Bojongasih');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21233', 'Kec. Culamega');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21234', 'Kec. Puspahiang');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21235', 'Kec. Jatiwaras');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21236', 'Kec. Mangunreja');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21237', 'Kec. Gunungtanjung');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21238', 'Kec. Karangjaya');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21239', 'Kec. Padakembang');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21240', 'Kec. Sukahening');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21241', 'Kec. Kadipaten');
INSERT INTO `wilayah` VALUES ('212', 'Kab. Tasikmalaya', '21242', 'Kec. Sukaresik');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21401', 'Kec. Cimerak');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21402', 'Kec. Cijulang');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21403', 'Kec. Cigugur');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21404', 'Kec. Langkaplancar');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21405', 'Kec. Parigi');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21406', 'Kec. Sidamulih');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21407', 'Kec. Pangandaran');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21408', 'Kec. Kalipucang');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21409', 'Kec. Padaherang');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21410', 'Kec. Banjarsari');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21411', 'Kec. Lakbok');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21412', 'Kec. Pamarican');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21413', 'Kec. Cidolog');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21414', 'Kec. Cimaragas');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21415', 'Kec. Cijeungjing');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21416', 'Kec. Cisaga');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21417', 'Kec. Tambaksari');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21418', 'Kec. Rancah');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21419', 'Kec. Rajadesa');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21420', 'Kec. Sukadana');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21421', 'Kec. Ciamis');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21422', 'Kec. Cikoneng');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21423', 'Kec. Cihaurbeuti');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21424', 'Kec. Sadananya');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21425', 'Kec. Cipaku');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21426', 'Kec. Jatinagara');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21427', 'Kec. Panawangan');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21428', 'Kec. Kawali');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21429', 'Kec. Panjalu');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21430', 'Kec. Panumbangan');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21431', 'Kec. Panjalu Utara/Sukamantri');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21432', 'Kec. Sindangkasih');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21433', 'Kec. Purwadadi');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21434', 'Kec. Baregbeg');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21435', 'Kec. Lumbung');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21436', 'Kec. Mangunjaya');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21437', 'Sukamantri');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21490', 'Padaherang');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21491', 'Kalipucang');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21492', 'Pangandaran');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21493', 'Sidamulih');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21494', 'Parigi');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21495', 'Cimerak');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21496', 'Cigugur');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21497', 'Langkaplancar');
INSERT INTO `wilayah` VALUES ('214', 'Kab. Ciamis', '21498', 'Mangunjaya');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21501', 'Kec. Darma');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21502', 'Kec. Kadugede');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21503', 'Kec. Ciniru');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21504', 'Kec. Selajambe');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21505', 'Kec. Subang');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21506', 'Kec. Ciwaru');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21507', 'Kec. Cibingbin');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21508', 'Kec. Luragung');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21509', 'Kec. Cidahu');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21510', 'Kec. Ciawigebang');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21511', 'Kec. Lebakwangi');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21512', 'Kec. Garawangi');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21513', 'Kec. Kuningan');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21514', 'Kec. Cigugur');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21515', 'Kec. Kramatmulya');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21516', 'Kec. Jalaksana');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21517', 'Kec. Cilimus');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21518', 'Kec. Mandirancan');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21519', 'Kec. Pasawahan');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21520', 'Kec. Pancalang');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21521', 'Kec. Cipicung');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21522', 'Kec. Kalimanggis');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21523', 'Kec. Japara');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21524', 'Kec. Karangkancana');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21525', 'Kec. Nusaherang');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21526', 'Kec. Cilebak');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21527', 'Kec. Hantara');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21528', 'Kec. Cimahi');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21529', 'Kec. Cibeureum');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21530', 'Kec. Sindangagung');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21531', 'Kec. Maleber');
INSERT INTO `wilayah` VALUES ('215', 'Kab. Kuningan', '21532', 'Kec. Cigandamekar');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21601', 'Kec. Lemahsugih');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21602', 'Kec. Bantarujeg');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21603', 'Kec. Cikijing');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21604', 'Kec. Talaga');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21605', 'Kec. Argapura');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21606', 'Kec. Maja');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21607', 'Kec. Majalengka');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21608', 'Kec. Cigasong');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21609', 'Kec. Sukahaji');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21610', 'Kec. Rajagaluh');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21611', 'Kec. Sindangwangi');
INSERT INTO `wilayah` VALUES ('216', 'Kab. Majalengka', '21612', 'Kec. Leuwimunding');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21736', 'Kec. Pasaleman');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21737', 'Kec. Pabuaran');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21738', 'Kec. Tengah Tani');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21739', 'Kec. Plered');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21740', 'Kec. Gempol');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21741', 'Kec. Greged');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21742', 'Kec. Suranenggala');
INSERT INTO `wilayah` VALUES ('217', 'Kab. Cirebon', '21743', 'Kec. Jamblang');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21801', 'Kec. Haurgeulis');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21802', 'Kec. Kroya');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21803', 'Kec. Gabuswetan');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21804', 'Kec. Cikedung');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21805', 'Kec. Lelea');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21806', 'Kec. Bangodua');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21807', 'Kec. Widasari');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21808', 'Kec. Kertasemaya');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21809', 'Kec. Krangkeng');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21810', 'Kec. Karangampel');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21811', 'Kec. Juntinyuat');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21812', 'Kec. Sliyeg');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21813', 'Kec. Jatibarang');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21814', 'Kec. Balongan');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21815', 'Kec. Indramayu');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21816', 'Kec. Sindang');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21817', 'Kec. Lohbener');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21818', 'Kec. Losarang');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21819', 'Kec. Kandanghaur');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21820', 'Kec. Bongas');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21821', 'Kec. Anjatan');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21822', 'Kec. Sukra');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21823', 'Kec. Arahan');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21824', 'Kec. Cantigi');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21825', 'Kec. Gantar');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21826', 'Kec. Terisi');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21827', 'Kec. Sukagumiwang');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21828', 'Kec. Kedokan Bunder');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21829', 'Kec. Pasekan');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21830', 'Kec. Tukdana');
INSERT INTO `wilayah` VALUES ('218', 'Kab. Indramayu', '21831', 'Kec. Patrol');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21901', 'Kec. Sagalaherang');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21902', 'Kec. Jalancagak');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21903', 'Kec. Cisalak');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21904', 'Kec. Tanjungsiang');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21905', 'Kec. Cijambe');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21906', 'Kec. Cibogo');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21907', 'Kec. Subang');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21908', 'Kec. Kalijati');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21909', 'Kec. Cipeundeuy');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21910', 'Kec. Pabuaran');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21911', 'Kec. Patokbeusi');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21912', 'Kec. Purwadadi');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21913', 'Kec. Cikaum');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21914', 'Kec. Pagaden');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21915', 'Kec. Cipunagara');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21916', 'Kec. Compreng');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21917', 'Kec. Binong');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21918', 'Kec. Ciasem');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21919', 'Kec. Pamanukan');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21920', 'Kec. Pusakanagara');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21921', 'Kec. Legon Kulon');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21922', 'Kec. Blanakan');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21923', 'Kec. Dawuan');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21924', 'Kec. Serangpanjang');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21925', 'Kec. Kasomalang');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21926', 'Kec. Tambakdahan');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21927', 'Kec. Pagaden Barat');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21928', 'Kec. Pusakajaya');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21929', 'Kec. Ciater');
INSERT INTO `wilayah` VALUES ('219', 'Kab. Subang', '21930', 'Kec. Sukasari');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22001', 'Kec. Jatiluhur');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22002', 'Kec. Maniis');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22003', 'Kec. Tegalwaru');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22004', 'Kec. Plered');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22005', 'Kec. Sukatani');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22006', 'Kec. Darangdan');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22007', 'Kec. Bojong');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22008', 'Kec. Wanayasa');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22009', 'Kec. Pasawahan');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22010', 'Kec. Purwakarta');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22011', 'Kec. Campaka');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22012', 'Kec. Sukasari');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22013', 'Kec. Kiarapedes');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22014', 'Kec. Babakancikao');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22015', 'Kec. Cibatu');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22016', 'Kec. Bungursari');
INSERT INTO `wilayah` VALUES ('220', 'Kab. Purwakarta', '22017', 'Kec. Pondok Salam');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22101', 'Kec. Pangkalan');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22102', 'Kec. Ciampel');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22104', 'Kec. Klari');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22105', 'Kec. Cikampek');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22106', 'Kec. Tirtamulya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22107', 'Kec. Jatisari');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22109', 'Kec. Lemahabang');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22110', 'Kec. Telagasari');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22111', 'Kec. Karawang');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22112', 'Kec. Rawamerta');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22113', 'Kec. Tempuran');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22114', 'Kec. Kutawaluya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22115', 'Kec. Rengasdengklok');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22116', 'Kec. Pedes');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22117', 'Kec. Cibuaya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22118', 'Kec. Tirtajaya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22119', 'Kec. Batujaya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22120', 'Kec. Pakisjaya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22121', 'Kec. Majalaya');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22122', 'Kec. Jayakerta');
INSERT INTO `wilayah` VALUES ('221', 'Kab. Karawang', '22123', 'Kec. Cilamaya Kulon');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26009', 'Kec. Buah Batu');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26010', 'Kec. Rancasari');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26011', 'Kec. Cibiru');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26012', 'Kec. Ujungberung');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26013', 'Kec. Arcamanik');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26015', 'Kec. Kiaracondong');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26016', 'Kec. Batununggal');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26017', 'Kec. Sumur Bandung');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26018', 'Kec. Andir');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26019', 'Kec. Cicendo');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26020', 'Kec. Bandung Wetan');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26021', 'Kec. Cibeunying Kidul');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26022', 'Kec. Cibeunying Kaler');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26023', 'Kec. Coblong');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26024', 'Kec. Sukajadi');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26025', 'Kec. Sukasari');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26026', 'Kec. Cidadap');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26027', 'Kec. Gedebage');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26028', 'Kec. Panyileukan');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26029', 'Kec. Cinambo');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26030', 'Kec. Mandalajati');
INSERT INTO `wilayah` VALUES ('260', 'Kota Bandung', '26031', 'Kec. Antapani');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26101', 'Kec. Kota Bogor Selatan');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26102', 'Kec. Kota Bogor Timur');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26103', 'Kec. Kota Bogor Utara');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26104', 'Kec. Kota Bogor Tengah');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26105', 'Kec. Kota Bogor Barat');
INSERT INTO `wilayah` VALUES ('261', 'Kota Bogor', '26106', 'Kec. Tanah Sereal');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26201', 'Kec. Baros');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26202', 'Kec. Citamiang');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26203', 'Kec. Warudoyong');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26204', 'Kec. Gunung Puyuh');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26205', 'Kec. Cikole');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26206', 'Kec. Lembur Situ');
INSERT INTO `wilayah` VALUES ('262', 'Kota Sukabumi', '26207', 'Kec. Cibeureum');
INSERT INTO `wilayah` VALUES ('263', 'Kota Cirebon', '26301', 'Kec. Harjamukti');
INSERT INTO `wilayah` VALUES ('263', 'Kota Cirebon', '26302', 'Kec. Lemahwungkuk');
INSERT INTO `wilayah` VALUES ('263', 'Kota Cirebon', '26303', 'Kec. Pekalipan');
INSERT INTO `wilayah` VALUES ('263', 'Kota Cirebon', '26304', 'Kec. Kesambi');
INSERT INTO `wilayah` VALUES ('263', 'Kota Cirebon', '26305', 'Kec. Kejaksan');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26501', 'Kec. Pondokgede');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26502', 'Kec. Jatiasih');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26503', 'Kec. Bantargebang');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26504', 'Kec. Bekasi Timur');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26505', 'Kec. Bekasi Selatan');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26506', 'Kec. Bekasi Barat');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26507', 'Kec. Bekasi Utara');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26508', 'Kec. Jati Sampurna');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26509', 'Kec. Medan Satria');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26510', 'Kec. Rawalumbu');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26511', 'Kec. Mustika Jaya');
INSERT INTO `wilayah` VALUES ('265', 'Kota Bekasi', '26512', 'Kec. Pondok Melati');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26601', 'Kec. Sawangan');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26602', 'Kec. Pancoran Mas');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26603', 'Kec. Sukmajaya');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26604', 'Kec. Cimanggis');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26605', 'Kec. Beji');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26606', 'Kec. Limo');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26607', 'Kec. Cipayung');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26608', 'Kec. Cilodong');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26609', 'Kec. Cinere');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26610', 'Kec. Tapos');
INSERT INTO `wilayah` VALUES ('266', 'Kota Depok', '26611', 'Kec. Bojongsari');
INSERT INTO `wilayah` VALUES ('267', 'Kota Cimahi', '26701', 'Kec. Cimahi Selatan');
INSERT INTO `wilayah` VALUES ('267', 'Kota Cimahi', '26702', 'Kec. Cimahi Tengah');
INSERT INTO `wilayah` VALUES ('267', 'Kota Cimahi', '26703', 'Kec. Cimahi Utara');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26801', 'Kec. Cibeureum');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26802', 'Kec. Tamansari');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26803', 'Kec. Kawalu');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26804', 'Kec. Mangkubumi');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26805', 'Kec. Indihiang');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26806', 'Kec. Cipedes');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26807', 'Kec. Cihideung');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26808', 'Kec. Tawang');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26809', 'Kec. Purbaratu');
INSERT INTO `wilayah` VALUES ('268', 'Kota Tasikmalaya', '26810', 'Kec. Bungursari');
INSERT INTO `wilayah` VALUES ('269', 'Kota Banjar', '26901', 'Kec. Banjar');
INSERT INTO `wilayah` VALUES ('269', 'Kota Banjar', '26902', 'Kec. Purwaharja');
INSERT INTO `wilayah` VALUES ('269', 'Kota Banjar', '26903', 'Kec. Pataruman');
INSERT INTO `wilayah` VALUES ('269', 'Kota Banjar', '26904', 'Kec. Langensari');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20516', 'Kec. Cariu');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20517', 'Kec. Jonggol');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20518', 'Kec. Cileungsi');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20519', 'Kec. Gunungputri');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20520', 'Kec. Citeureup');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20510', 'Kec. Ciawi');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20511', 'Kec. Cisarua');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20512', 'Kec. Megamendung');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20513', 'Kec. Sukaraja');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20514', 'Kec. Babakan Madang');
INSERT INTO `wilayah` VALUES ('205', 'Kab. Bogor', '20515', 'Kec. Sukamakmur');
